config/routes.rb
Rails.application.routes.draw do

  root to: 'employees#index'

  resources :employees
  resources :organisations do
    resources :employees
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :organisation
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, length: { in: 7..15 }
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  has_many :employees
  validates :name, presence: true
  validates :address, presence: true
  validates :phone, presence: true, length: { in: 7..15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    if params[:organisation_id]
      @employee.organisation = Organisation.find(params[:organisation_id])
    end
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :address, :phone, :organisation_id)
    end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: [:show, :edit, :update, :destroy]

  # GET /organisations
  # GET /organisations.json
  def index
    @organisations = Organisation.all
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
  end

  # GET /organisations/new
  def new
    @organisation = Organisation.new
  end

  # GET /organisations/1/edit
  def edit
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { render :new }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisations/1
  # PATCH/PUT /organisations/1.json
  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { render :edit }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation.destroy
    respond_to do |format|
      format.html { redirect_to organisations_url, notice: 'Organisation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisation
      @organisation = Organisation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organisation_params
      params.require(:organisation).permit(:name, :address, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name, class: "required" %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name, class: "required" %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :organisation_id %>
    <%= f.select :organisation_id, Organisation.all.collect {|o| [o.name, o.id]}, {include_blank: true} %>
    <div>Not on the list?
      <%= link_to 'Add new organisation', new_organisation_path %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "add person", class: "btn" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing All People</h1>

<% if @employees.length == 0 %>
  <div>Please add a new person</div>
<% else %>
  <table>
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Address</th>
        <th>Phone</th>
        <th>Organisation</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.first_name %></td>
          <td><%= employee.last_name %></td>
          <td><%= employee.address %></td>
          <td><%= employee.phone %></td>
          <td><% if employee.organisation %><%= employee.organisation.name %><% end %></td>
          <td><%= link_to 'Show', employee, class: 'btn btn--secondary' %></td>
          <td><%= link_to 'Edit', edit_employee_path(employee), class: 'btn' %></td>
          <td><%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn--warning' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<br>
<div class='link-block'>
  <%= link_to 'New Person', new_employee_path, class: 'btn' %>
  <%= link_to 'Organisations', organisations_path, class: 'btn btn--secondary' %>
</div>

app/views/employees/new.html.erb
<h1>New Employee <% if @employee.organisation %>in <%= @employee.organisation.name %> <% end %></h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @employee.first_name %>
  <%= @employee.last_name %>
</h1>
<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Organisation:</strong>
  <% if @employee.organisation.blank? %>
    None
  <% else %>
    <%= @employee.organisation.name %>
    </br>
    </br>
    <%= link_to 'See all employees at ' + @employee.organisation.name, @employee.organisation, class: 'btn btn--secondary' %>
  <% end %>
</p>

<div class='link-block'>
  <%= link_to 'Edit', edit_employee_path(@employee), class: 'btn' %>
  <%= link_to 'Organisations', organisations_path, class: 'btn btn--secondary' %>
  <%= link_to 'People', employees_path, class: 'btn btn--secondary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/organisations/_form.html.erb
<%= form_for(@organisation) do |f| %>
  <% if @organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
      <% @organisation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, class: "required" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address, class: "required" %>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :phone, class: "required" %>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit "add organisation", class: "btn" %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h1>Editing Organisation</h1>

<%= render 'form' %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>

app/views/organisations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing All Organisations</h1>

<% if @organisations.length == 0 %>
  <div>Please add a new organisation</div>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Phone</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @organisations.each do |organisation| %>
        <tr>
          <td><%= organisation.name %></td>
          <td><%= organisation.address %></td>
          <td><%= organisation.phone %></td>
          <td><%= link_to 'Show', organisation, class: 'btn btn--secondary' %></td>
          <td><%= link_to 'Edit', edit_organisation_path(organisation), class: 'btn' %></td>
          <td><%= link_to 'Delete', organisation, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn--warning' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<br>
<div class='link-block'>
  <%= link_to 'New Organisation', new_organisation_path, class: 'btn' %>
  <%= link_to 'People', employees_path, class: 'btn btn--secondary' %>
</div>

app/views/organisations/new.html.erb
<h1>New Organisation</h1>

<%= render 'form' %>

<%= link_to 'Back', organisations_path %>

app/views/organisations/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @organisation.name %>
</h1>

<p>
  <strong>Name:</strong>
  <%= @organisation.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @organisation.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @organisation.phone %>
</p>
<% if @organisation.employees.length > 0 %>
  <p>
    <strong>Employees:</strong>
      <table>
        <thead>
          <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Address</th>
            <th>Phone</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @organisation.employees.each do |employee| %>
            <tr>
              <td><%= employee.first_name %></td>
              <td><%= employee.last_name %></td>
              <td><%= employee.address %></td>
              <td><%= employee.phone %></td>
              <td><%= link_to 'Show', employee, class: 'btn btn--secondary' %></td>
              <td><%= link_to 'Edit', edit_employee_path(employee), class: 'btn' %></td>
              <td><%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn--warning' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </ul>
  </p>
<% end %>

<div class='link-block'>
  <%= link_to 'Add Employee', new_organisation_employee_path(@organisation), class: 'btn btn--secondary' %>
  <%= link_to 'Edit', edit_organisation_path(@organisation), class: 'btn btn--secondary' %>
  <%= link_to 'Organisations', organisations_path, class: 'btn' %>
  <%= link_to 'People', employees_path, class: 'btn' %>
</div>